global:
  docker_repo:
  max_pod_retrials: 3
assignment:
# Seurat
- tools_id:
   - seurat-read10x
  docker_repo_override: quay.io
  docker_owner_override: ebigxea
  docker_image_override: r-seurat-scripts
  docker_tag_override: 0.0.1--0
  max_pod_retrials: 3
